### ISSUE TITLE
Can not download datasets and models

### ISSUE THREAD

**Issue by roidnishikawa** [KaiyangZhou/vsumm-reinforce#20]
Hello, the file datasets.tar.gz and model can't be downloaded. I can't find your mailbox on the homepage. Could you provide it again? Or send me an email. My email address is: 
nishikawa@roid.co.jp
Thank you.

**Comment by SinDongHwan** [comment]
Hi^^
I think dataset is same about "https://github.com/KaiyangZhou/pytorch-vsumm-reinforce"
you can download dataset link is [this](https://1drv.ms/u/s!Au4J1yd2Q9NvlXntbbKow1QnmpBo?e=c7Aa7R)
this is my onedrive.^^
Good Luck^^

**Comment by roidnishikawa** [comment]
Hello,
Thank you for early response.

> I think dataset is same about "https://github.com/KaiyangZhou/pytorch-vsumm-reinforce"
> you can download dataset link is [this](https://1drv.ms/u/s!Au4J1yd2Q9NvlXntbbKow1QnmpBo?e=c7Aa7R)

Thank you so much.
How about models?
Did you make it just by below option?

python vsum_train.py --dataset datasets/eccv16_dataset_tvsum_google_pool5.h5 --max-epochs 60 --hidden-dim 256

**Comment by SinDongHwan** [comment]
Good~! 
i just used pytorch version.

**Comment by roidnishikawa** [comment]
Thank you.
I've got made models by that command.
theano0.9.0
numpy1.3.0

**Comment by meisa233** [comment]
> Thank you.
> I've got made models by that command.
> theano0.9.0
> numpy1.3.0

Hello, I also need this model to accomplish my research.
Can you give it?
Thank you.

**Comment by Willy0919** [comment]
> Hi^^
> I think dataset is same about "https://github.com/KaiyangZhou/pytorch-vsumm-reinforce"
> you can download dataset link is [this](https://1drv.ms/u/s!Au4J1yd2Q9NvlXntbbKow1QnmpBo?e=c7Aa7R)

Hi, I have used your link, but the file size is 165M, and when I load it, the keys are null. Have you ever encountered the problem?

**Comment by meisa233** [comment]
The file size of the file I downloaded is&nbsp;173.5 MB.Is your file destroyed?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Li Wang"<notifications@github.com&gt;; 
发送时间: 2019年11月13日(星期三) 下午5:07
收件人: "KaiyangZhou/vsumm-reinforce"<vsumm-reinforce@noreply.github.com&gt;; 
抄送: "MEISA"<610878158@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [KaiyangZhou/vsumm-reinforce] Can not download datasets and models (#20)



 
Hi^^
 I think dataset is same about "https://github.com/KaiyangZhou/pytorch-vsumm-reinforce"
 you can download dataset link is this
  
Hi, I have used your link, but the file size is 165M, and when I load it, the keys are null. Have you ever encountered the problem?

**Comment by SinDongHwan** [comment]
@meisa233 
Hi, 
my file is not destroyed. 
size is 173.5MB.
why??

**Comment by meisa233** [comment]
I don't known the reason.
This is the link of my file.
https://drive.google.com/open?id=16ntGzuxs6L-2o3E5Na6FYhtPJGxgrTYh
You can download it.






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shin Donghwan"<notifications@github.com&gt;; 
发送时间: 2019年11月13日(星期三) 下午5:40
收件人: "KaiyangZhou/vsumm-reinforce"<vsumm-reinforce@noreply.github.com&gt;; 
抄送: "MEISA"<610878158@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [KaiyangZhou/vsumm-reinforce] Can not download datasets and models (#20)




@meisa233
 Hi,
 my file is not destroyed.
 size is 173.5MB.
 why??

**Comment by SinDongHwan** [comment]
@meisa233 
i can't download your link, because of access permission.

what is your question?
you can't download dataset on my link?

173.5MB is correct.

**Comment by meisa233** [comment]
Sorry, I just reply following the instructions in the email( "You are receiving this because you were mentioned.
Reply to this email directly,&nbsp;view it on GitHub, or&nbsp;unsubscribe.")I found the sender has changed just now.
I received a email "Hi, I have used your link, but the file size is 165M, and when I load it, the keys are null. Have you ever encountered the problem?"
So I replied. However, the sender has changed.(original sender is&nbsp;Li Wang)
I am really sorry for the trouble.






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shin Donghwan"<notifications@github.com&gt;; 
发送时间: 2019年11月13日(星期三) 晚上7:10
收件人: "KaiyangZhou/vsumm-reinforce"<vsumm-reinforce@noreply.github.com&gt;; 
抄送: "MEISA"<610878158@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [KaiyangZhou/vsumm-reinforce] Can not download datasets and models (#20)




@meisa233
 i can't download your link, because of access permission.
 
what is your question?
 you can't download dataset on my link?
 
173.5MB is correct.

**Comment by SinDongHwan** [comment]
@meisa233 
no~!!  I'm okay.^^
i just wanted to know your mention.^^

**Comment by anbuharry** [comment]
How can i dowmload models ?????
